repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--quiet"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files", "--quiet"]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        types_or: [python]
        require_serial: true

default_language_version:
    python: python3.11
