version: "3"

services:
  app:
    container_name: sag-dashboard
    build: .
    volumes:
      - "${PWD}/config.json:/app/config.json"
    working_dir: /app
    restart: always
    ports:
      - "8000:8000"
