[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "mypy>=1.1.1",
    "black>=23.3.0",
    "pytest>=7.2.2",
    "debugpy>=1.6.6",
    "types-python-dateutil>=2.8.19.11",
    "types-requests>=2.28.11.17",
]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "bobokrut", email = "egor-evlampiev@mail.ru"},
]
dependencies = [
    "setuptools>=67.6.1",
    "wheel>=0.40.0",
    "orjson>=3.8.9",
    "dash>=2.9.2",
    "requests>=2.28.2",
    "polars>=0.16.18",
    "pydantic>=1.10.7",
    "flask-login>=0.6.2",
    "python-dateutil>=2.8.2",
    "pandas>=1.5.3",
    "python-dotenv>=1.0.0",
    "iso6709>=0.1.5",
    "asgiref>=3.6.0",
    "uvicorn>=0.22.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}


[tool.black]
target-version = ["py311"]

[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.11"

