[tool.poetry]
name = "sag-dashboard"
version = "0.1.0"
description = ""
authors = ["bobokrut <egor-evlampiev@mail.ru>"]
readme = "README.md"
packages = [{include = "sag_dashboard"}]

[tool.poetry.dependencies]
python = "^3.11"
asgiref = {version = "3.6.0", python = "3.11", platform = "linux"}
dash = {version = "2.9.3", python = "3.11", platform = "linux"}
flask = {version = "2.2.3", python = "3.11", platform = "linux"}
iso6709 = {version = "0.1.5", python = "3.11", platform = "linux"}
orjson = {version = "3.8.12", python = "3.11", platform = "linux"}
pandas = {version = "2.0.1", python = "3.11", platform = "linux"}
pydantic = {version = "1.10.7", python = "3.11", platform = "linux"}
python-dotenv = {version = "1.0.0", python = "3.11", platform = "linux"}
requests = {version = "2.30.0", python = "3.11", platform = "linux"}
uvicorn = {version = "0.22.0", python = "3.11", platform = "linux"}
flask-login = "^0.6.2"
setuptools = "^68.0.0"
polars = "^0.19.1"
pyarrow = "^13.0.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.3.1"
debugpy = "^1.6.7"
memory-profiler = "^0.61.0"
matplotlib = "^3.7.1"
memray = "^1.7.0"
filprofiler = "^2023.3.1"
isort = "^5.12.0"
ruff = "^0.0.277"


[tool.poetry.group.extra.dependencies]
jsonschema = "^4.17.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
target-version = ["py311"]

[tool.pyright]
typeCheckingMode = "basic"
venvPath = "/home/bobokrut/.cache/pypoetry/virtualenvs"
venv = "sag-dashboard-pSCj5UPf-py3.11"
pythonVersion = "3.11"
useLibraryCodeForTypes = false

[tool.pytest.ini_options]
addopts = "-r x"

[tool.ruff]
select = ["E", "F", "T20"]
ignore = ["E402", "E501"]


